Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "MyServiceS3Bucket"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: 'arn:aws:kms:us-east-1:123456789:key/056ea50b-1013-3907-8617-c93e474e400'
      Tags:
        - Key: "stage"
          Value: "prod"
        - Key: "service"
          Value: "myService"
  MyGp2Volume:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: "us-west-2b"
      Encrypted: "true"
      Size: 10
      VolumeType: "gp2"
  MyIo1Volume:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: "us-west-2b"
      Encrypted: "true"
      Iops: 1000
      Size: 30
      VolumeType: "io1"